index:
  per_page: 10
user:
  avatar:
    size: 50
    show_follow_size: 30
  name:
    maximum: 50

  email:
    maximum: 255
    regex: '\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z'

  password:
    minimum: 6

  follow:
    show:
      size: 10
static_pages:
  home:
    maximum: 10
mailer:
  default_from: "noreply@gmail.com"
  password_reset:
    expired_time: 2.hours
micropost:
  content:
    maximum: 140
  image:
    content_types: ["image/jpg", "image/jpeg", "image/png"]
    accept: "image/jpeg,image/gif,image/png"
    display:
      resize: [500, 500]
    max_size: 5
